### PR TITLE
Crossy_road_Game Added

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## Related Issue*

#478 

## Description

Crossy_road_Game Added

## Screenshot Section

Crossy_Road_Game

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/114821855/6cc35d45-4a88-40e7-865e-83918546da0d

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@Kalivarapubindusree Resoleve the conflict and remove credit name

**Comment by Kalivarapubindusree** [comment]
It doesn't shows any conflict for me @Durgesh4993

**Comment by Kalivarapubindusree** [comment]
Will u please tell me where I did mistake?? @Durgesh4993

**Comment by Kalivarapubindusree** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/pull/537

**Pull request closed without merging**
