### PR TITLE
added Stacker game 👍

### LINKED ISSUE #605: [New game]: Stacker game
### 🎮 Game Request

Stacker game uses just html and css, at every level a group of boxes moves on a 10x10 grid.

### Point down the features

Have to catch the speed of the boxes which are moving and have to freeze them at our desired place. This game's goal is to challenge the speed of player's vision and skills to make to the top of the stack.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by sabhisharma-ise**
## Related Issue*

Closes #605 

## Description

Added Stacker game in the repo (See the video below for reference)

## Screenshot Section

Stacker

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/100849696/c1052e12-b1dc-4fb0-bf68-bd30d24c6e30

## Checklist 

- [X] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [X] I have added game into "additionalpage/game.html"*
- [X] I have added Update main README.md file*
- [X] I have included comments in areas that may be difficult to understand.
- [X] My changes have not introduced any new warnings.
- [X] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@sabhisharma-ise 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by sabhisharma-ise** [comment]
@Durgesh4993 Hello, please can you review this PR and merge it!

**Comment by sabhisharma-ise** [comment]
@Durgesh4993 Everytime I'm resolving the conflicts, after merging someone'else PR, new merge conflicts arise. So, I request you to first merge my PR and than look at other PR (because I'm waiting from 3 days)

**Comment by Durgesh4993** [comment]
@sabhisharma-ise 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by sabhisharma-ise** [comment]
@Durgesh4993 Sir, please Merge this PR!

**Comment by sabhisharma-ise** [comment]
@Durgesh4993 Hello, no response from your side !

**Pull request merged**
