### PR TITLE
added redirection link

### LINKED ISSUE #960: [Feature Request] : footer redirection is not working
## About Feature
Footer redirection is not working I would like to fix it.
## Technologies Used
html
## Screenshot
image

## Connect Us On Social Media -
- [ ]  Star the repositry
- [x]  <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]   <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]   <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]    <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### PR DESCRIPTION
**Pull request by agastya3636**
## Related Issue*

Closes #960 

## Description
added the redirection links.

## Checklist 

- [ ] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [ ] I have added game into "additionalpage/game.html"*
- [ ] I have added Update main README.md file*

## Task

- [ ] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [ ]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [ ]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn:
<br>GitHub: https://github.com/agastya3636
<br>YouTube:
<br>Discord:

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Connect Us :
LinkedIn: https://www.linkedin.com/company/chromegaming
GitHub: https://github.com/GameSphere-MultiPlayer

Thank you :)

**Comment by agastya3636** [comment]
@Durgesh4993 please merge it and close the issue

**Comment by agastya3636** [comment]
@Durgesh4993 @Amancoder-01 my pr is not showing on the leaderboard could you help me?

**Pull request merged**
