### PR TITLE
Added Games News using `API`

### LINKED ISSUE #680: Adding a Gaming News page {with API}
Hello @Durgesh4993 ,
I'm adding a Gaming News Section which is going to connect the API and fetch  data and news about the game news and this change something we need in this website because there is section of game news in the website and I'm adding a Game News Section which help gamers to be up to date. 👍🏻 

## Screenshot -
image

### Soon raise a PR kindly assign this to me.

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
## Related Issue #680 

Closes #680

## Description
Hello @Aman1-coder ,
I have added a Game News Section using API and it's fetches data from the Server and gives the latest information about games.
## Screenshot -
image

## Video - 
[Screencast from 01-07-23 03:17:13 PM IST.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/121503426/4855222a-1731-483b-956d-75f2e3a6db5c)

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
@Aman1-coder `API` is a bridge between frontend and the backend so if you increase my level as per the task it will really appreciated. Hope you'll understand and will increase my level as per this `PR`

**Comment by Durgesh4993** [comment]
@SyedImtiyaz-1 Don't change the page you can add API into home page in Latest News section

**Comment by SyedImtiyaz-1** [comment]
Sure

**Comment by Durgesh4993** [comment]
And one more thing give a button for read

**Comment by SyedImtiyaz-1** [comment]
> And one more thing give a button for read
Okay Working on this. 👍🏻

**Comment by SyedImtiyaz-1** [comment]
@Durgesh4993 ,
I have successfully done all the changes here is the Video -
[Screencast from 01-07-23 11:33:46 PM IST.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/121503426/5930e0be-c78d-43c6-895a-8dd75aa3f338)

`It is fetching the data from the news API ` 👍🏻 
`I think level 2 will be really appreciated`

**Comment by SyedImtiyaz-1** [comment]
@Durgesh4993 ,
Please review this.

**Comment by Durgesh4993** [comment]
@SyedImtiyaz-1 May i know, when we click on read more then why game is on instead of article

**Comment by Durgesh4993** [comment]
It not showing News, may i know why

**Comment by Durgesh4993** [comment]
image

**Comment by Durgesh4993** [comment]
Please resolve this issue

**Comment by SyedImtiyaz-1** [comment]
Issue Resolved ! 👍🏻

**Pull request merged**
