### PR TITLE
Fixed Newsletter Form. Issue #935

### LINKED ISSUE #935: [Feature Request] : The newsletter form is submitting even if it is empty.
## About Feature
Issue in the News letter form.

## Description
- The news letter form is getting submitted even if it is not filled (Empty Form without email is submitted).
 

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/126074487/5f18f327-2120-4f7a-8b0b-a20b310a4abe

### Please assign this issue to me.

### PR DESCRIPTION
**Pull request by vishanurag**
## Related Issue*

Closes #935

## Description
- Fixed the newsletter form issue.
- Now the form requires email to be submitted.

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/126074487/a154c972-f615-4bc0-9b7b-a497444dfae7

LinkedIn: [Anurag Vishwakarma](https://linkedin.com/in/anuragvishwakarma/)
<br>GitHub: [Anurag Vishwakarma](https://github.com/vishanurag)

## Please merge this pull request.

### CODE REVIEW

**Comment by vishanurag** [comment]
Please add GSSOC lebels.

**Comment by vishanurag** [comment]
@Durgesh4993 Please review and merge my pull request.

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Connect Us :
LinkedIn: https://www.linkedin.com/company/chromegaming
GitHub: https://github.com/GameSphere-MultiPlayer

Thank you :)

**Pull request merged**
