### PR TITLE
Added Ravoucs Raven RunGame 👾

### LINKED ISSUE #596: [New game]: Ravoucs Raven Run
### 🎮 Game Request

"Raucous Raven Run" is an endless running game where players control a brave bird flying through the sky, attempting to avoid a flock of mischievous ravens. The game features smooth gameplay, comical animations, a variety of ravens with different sizes and colors, and an enjoyable soundtrack. Players must dodge and maneuver skillfully to avoid colliding with the ravens and earn a high score. Getting hit by a raven triggers amusing and explosive animations, adding an extra layer of entertainment to the game.

Adding "Raucous Raven Run" to the Gamesphere Project would enhance the diversity of available games and provide users with a fun and lighthearted gaming experience.

### Point down the features

Game points
Features
-Smooth gameplay
-Comical animations
-Variety of ravens
-Soundtrack

Informatician and 4 more pages - Personal - Microsoft​ Edge 27-06-2023 20_27_06

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Related Issue*

Closes #596 

## Description

This pull request adds the exciting "Firedog Adventure" game to our project. Get ready for a thrilling experience that will test your skills and bring a smile to your face!

- Play as a courageous firedog soaring through the skies.
- Encounter mischievous flaming ravens as your fiery avian foes.
- Ravens come in various sizes and vibrant colors with dazzling sparks trails.
- Skillfully maneuver to avoid collisions with the ravens.
- Aim to achieve the highest score possible.
- Enjoy explosive and hilarious animations when hit by a raven.
- Resume gameplay after getting hit and continue your Firedog Adventure.

## Screenshot Section

Informatician and 4 more pages - Personal - Microsoft​ Edge 27-06-2023 20_27_06

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Add this game into additionalpage/game.htm

**Comment by Nishitbaria** [comment]
> Add this game into additionalpage/game.htm

Hey  @Durgesh4993  I have added Game in `additionalpage/game.htm`

**Comment by Nishitbaria** [comment]
> @Durgesh4993 already merged in [kunjgit/GameZone#2111](https://github.com/kunjgit/GameZone/pull/2111)

@Killer2-O  what is the problem?

**Comment by Nishitbaria** [comment]
> Dont make spam pr's

First fall it's not spam second think there are so many rule that Breck go to discord ask the Gssoc Team because There Mangment team is responsible not mine There are so many peoples doing this any it's not spem if I start couting this things na all top 20 people will be banned

**Comment by Nishitbaria** [comment]
> Dont make spam pr's

@Killer2-O 
If you use your mind in contribution na then you not writing this line that not make sense I know I come in top 5 that vice you are doing this stupid things Spam vam 🥱

**Comment by Nishitbaria** [comment]
> Dont make spam pr's

@Killer2-O  Go to my profile And see  and my good contribution learn that so many things that I have add value addition in project you have to learn those things doing stupid things not give you anything😶‍🌫️

**Pull request merged**
