### PR TITLE
Egg Catch Game Added

### LINKED ISSUE #636: [New game] [Egg Catcher Game]:
### 🎮 Game Request

Game logic and basic description

Eggs Catcher is a classic game where the goal is to catch as many eggs as possible. In this game, every egg you catch will increase your score and if you miss 5 eggs you will lose the game.

### Point down the features

Game points

Good GUI
Record your Score
Lives

image

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by JadavShraddha**
## Related Issue*

Closes #636 

## Description
Eggs Catcher is a classic game where the goal is to catch as many eggs as possible. In this game, every egg you catch will increase your score and if you miss 5 eggs you will lose the game.

## Screenshot Section
image

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Please resolve conflict

**Comment by JadavShraddha** [comment]
How can update forked repository?

**Comment by Durgesh4993** [comment]
@JadavShraddha You can delete or refork it is easy to you

**Comment by JadavShraddha** [comment]
ohk

**Comment by Durgesh4993** [comment]
@JadavShraddha 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by Durgesh4993** [comment]
and also resolve conflict

**Pull request closed without merging**
