### PR TITLE
added Preloader

### LINKED ISSUE #582: [New Feature]: website requires Preloader
### Describe your question or ask for support.❓

the website takes a bit of time to load, so I suggest we should add a *preloader* to the website.

Please assign me this issue under Gssoc'23 contributor.

### Select The Game Type

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by yashpreet2707**
closes #582

### CODE REVIEW

**Comment by yashpreet2707** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/111020648/3c66433e-bf74-45b2-ac90-8a9a05347eb2

**Comment by Aman1-coder** [comment]
@yashpreet2707 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by yashpreet2707** [comment]
done @Aman1-coder

**Comment by Durgesh4993** [comment]
@yashpreet2707 could you please check the reloder is not disable after the load of website

**Comment by yashpreet2707** [comment]
@Durgesh4993 It is not disabled just it's z-Index is changed to -2

**Comment by yashpreet2707** [comment]
@Durgesh4993 It is not disabled just it's z-Index is changed to -2.

Disabled means setting display: none ;    right ?

**Pull request merged**
