### PR TITLE
New Feature Added Search Bar

### PR DESCRIPTION
**Pull request by PatilHarshh**
## Related Issue*
#494 

Closes #issue_number

## Checklist 

- [ ] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [ ] I have added game into "additionalpage/game.html"*
- [ ] I have added Update main README.md file*
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by PatilHarshh** [comment]
@Durgesh4993 Please check

**Comment by Durgesh4993** [comment]
Send a demo vedio

**Comment by PatilHarshh** [comment]
ok

**Comment by PatilHarshh** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/120102234/85ea41a1-e2b8-4574-baf8-eec91157f87f

**Comment by PatilHarshh** [comment]
@Durgesh4993 please check

**Comment by PatilHarshh** [comment]
@Durgesh4993 I did not add search bar in multigame section i will raise another pr for ( because i saw no game there)

**Comment by Durgesh4993** [comment]
Could you please decorate, because it is to simply and also add it in multiplayer section

**Pull request closed without merging**
