### PR TITLE
Added Spider Man Game

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
#Issue No. #600 

## Description
I have added the Spider Man Go Game. 

## Screenshot - 
Screenshot from 2023-06-26 01-27-35

## Demo Video -
[Screencast from 26-06-23 01:27:41 AM IST.webm](https://github.com/GameSphere-MultiPlayer/GameSphere/assets/121503426/a9177c1f-234e-40c3-a113-1f0870df37fb)

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Aman1-coder** [comment]
@SyedImtiyaz-1
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 Follow Us on Social Media: LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/ GitHub:https://github.com/GameSphere-MultiPlayer

Done 👍🏻

**Comment by SyedImtiyaz-1** [comment]
@Durgesh4993 It is ready to merge 👍🏻

**Comment by SyedImtiyaz-1** [comment]
@Durgesh4993 ,
I have added my own PR without stealing any rights.
image

### Thank You !

**Comment by SyedImtiyaz-1** [comment]
> @Durgesh4993 @SyedImtiyaz-1 But you can't contribute the same project to multiple projects. Its in GSSoC guidelines.
> 
> @gurjeetsinghvirdee

Check the code base it's different.

**Comment by SyedImtiyaz-1** [comment]
@Okay @killer2O  AKA @Killer2OP ,
no problem let the Admin decide the stuff.
### I don't want any kind of conversation with you.

**Comment by Killer2OP** [comment]
> Okay @killer2O AKA @Killer2OP , no problem **let the Admin decide the stuff.** I don't want any kind of conversation with you.

If you still think that I am that guy kindly check https://github.com/pranjay-poddar/Dev-Geeks/pull/2198

**Comment by SyedImtiyaz-1** [comment]
> > Okay @killer2O AKA @Killer2OP , no problem **let the Admin decide the stuff.** I don't want any kind of conversation with you.
> 
> If you still think that I am that guy kindly check [pranjay-poddar/Dev-Geeks#2198](https://github.com/pranjay-poddar/Dev-Geeks/pull/2198)

Okay.

**Comment by SyedImtiyaz-1** [comment]
@SahityaRoy ,
He is a bot or a spammer please ignore this as you can see he is blocked from GITHUB now, and also it's name changed to Ghost.

His is ID : @Killer2O (which is not opening now.)

### Proof : 
[Screencast from 02-07-23 05:03:03 PM IST.webm](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/121503426/c325688c-a611-49c5-a79e-b5e7802e5692)

**Pull request merged**
