### PR TITLE
Added slide puzzle game

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Added the game successfully

closes issue number #240

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@Abhinavcode13 add screenshort on Single player/Banner - Image section

**Comment by Durgesh4993** [comment]
and also send a working demo vedio

**Comment by Durgesh4993** [comment]
Home page of game

**Comment by Abhinavcode13** [comment]
ok @Durgesh4993

**Comment by Abhinavcode13** [comment]
Video :
https://www.loom.com/share/513e5c714a26429f9b1382ab06d5d12b

home page img :
image

**Comment by Abhinavcode13** [comment]
@Durgesh4993 check now please

**Comment by Durgesh4993** [comment]
@Abhinavcode13 Please add this screnshort into "Sinleplayers-Banner- Image folder"

**Pull request merged**
