### PR TITLE
Feature : Search Bar Added

### PR DESCRIPTION
**Pull request by PatilHarshh**
## Related Issue*

Closes #issue_number  #494

## Checklist 

- [ ] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [ ] I have added game into "additionalpage/game.html"*
- [ ] I have added Update main README.md file*
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by PatilHarshh** [comment]
Screenshot (103)

**Comment by PatilHarshh** [comment]
@Durgesh4993 Now You should bless me , Now Search Bar changes its colors with theme Colors which looks amazing, please review my work

**Comment by Durgesh4993** [comment]
@PatilHarshh No it, not looking good,

**Comment by PatilHarshh** [comment]
@Durgesh4993 can you share you search design so that i make changes accordingly

**Comment by PatilHarshh** [comment]
> @PatilHarshh No it, not looking good,could you please add this search bar into navigation bar and when we tap on search button then search bar open

oh sure, @Durgesh4993 you want search icon at center or what1?

**Comment by Durgesh4993** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/98798977/a18e10b1-a2f1-41ca-a841-9b2a385a1ab0

Be like that

**Comment by PatilHarshh** [comment]
> 24.06.2023_17.59.49_REC.mp4 
> Be like that

sure i will try to work on it , icon should be at centre write ?

**Comment by Durgesh4993** [comment]
And one more thing please add this search bar into corner not center

**Comment by PatilHarshh** [comment]
> And one more thing please add this search bar into corner not center

ok

**Comment by Durgesh4993** [comment]
are you able to create a filter section also

**Comment by PatilHarshh** [comment]
> are you able to create a filter section also

please provide more info

**Comment by PatilHarshh** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/120102234/d513497a-927a-4856-99d6-d22a6d0fd8aa

**Comment by PatilHarshh** [comment]
@Durgesh4993 please review

**Comment by PatilHarshh** [comment]
@Durgesh4993 this was level 3 right !?

**Pull request merged**
