### PR TITLE
[GSSoC'23] Bingo game Completed !

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
@Durgesh4993 @mahamat-abdelkerim-abakar @Punnya1 

Sirs, I have completed the bingo game task within 3 days.

Bingo Game with different implementations :-

1. I am added the functionality for the multiplayer player.

2. Also added the background music for the same.

3. Also making the website of the Bingo-Game responsive for the mobile users also

4. Adding animations using CSS and JS

5. Creating a congratulation page at the end of the project with full of animations

6. At the end, adding music controls buttons and sliders to control the sound of the music.

**So, Please review my changes and Merge This Pull Request**

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@Avdhesh-Varshney could you please send me a demo vedio

**Comment by Avdhesh-Varshney** [comment]
Sir Video Link :- https://drive.google.com/file/d/19UG8MYhlP15irIewnH1wmm76iOII8dEw/view?usp=sharing

**Comment by Avdhesh-Varshney** [comment]
@Durgesh4993 Can you please tell me how this pull request is invalid ?
I am waiting for your response...

**Comment by Durgesh4993** [comment]
@Avdhesh-Varshney Because of spam, You have send same PR to gamezone that why

**Comment by Durgesh4993** [comment]
@Avdhesh-Varshney This instruction is given by Gurjeet

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney This instruction is given by Gurjeet

@Durgesh4993 Sir, but you know it is created by me only still adding `invalid` label on it.

**Pull request merged**
