### PR TITLE
Highway race - Barrel Dodge GSSOC'23

### LINKED ISSUE #713: [New game]: Highway Race - Barrel Dodge GSSOC'23
### 🎮 Game Request

Highway Race: Barrel Dodge is an exciting racing game where you control a car speeding along a highway, and your goal is to avoid barrels that appear on the road. Test your reflexes and see how far you can go! 

### Point down the features

The objective of Highway Race: Barrel Dodge is to maneuver your car through a busy highway, avoiding barrels that obstruct your path. The longer you survive without colliding with a barrel, the higher your score.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by srujana-16**
## Related Issue*

Closes #713 

## Description

New game added. 
Highway Race: Barrel Dodge is an exciting racing game where you control a car speeding along a highway, and your goal is to avoid barrels that appear on the road. Test your reflexes and see how far you can go! The objective of Highway Race: Barrel Dodge is to maneuver your car through a busy highway, avoiding barrels that obstruct your path. The longer you survive without colliding with a barrel, the higher your score.

## Screenshot Section

Highway_Race

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@srujana-16 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Comment by srujana-16** [comment]
Please add it as part of GSSOC'23

**Comment by Durgesh4993** [comment]
@srujana-16 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by srujana-16** [comment]
I have resolved the conflicts, please check and merge it.

**Comment by Durgesh4993** [comment]
@srujana-16 I think yo frgot to follow us

**Comment by srujana-16** [comment]
done

**Pull request merged**
