### PR TITLE
ADDED CLASSIC GAME SNAKE

### LINKED ISSUE #734: [New game]: Classic game Snake
### 🎮 Game Request

Game logic and basic description - This is a basic implementation of the classic "Snake" game using the Pygame library in Python. 

### Point down the features

Game points - It provides a simple window, a controllable snake, food to eat, and basic collision detection

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Shikhar9425**
## Related Issue*

Closes #734 

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Shikhar9425** [comment]
@mahamat-abdelkerim-abakar [ADDED CLASSIC GAME SNAKE]

**Comment by Durgesh4993** [comment]
@Shikhar9425 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by Shikhar9425** [comment]
@mahamat-abdelkerim-abakar please merge this pr

**Comment by Shikhar9425** [comment]
> @Shikhar9425 Follow Us on Social Media: LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/ GitHub:https://github.com/GameSphere-MultiPlayer

already done @Durgesh4993

**Comment by Shikhar9425** [comment]
> @mahamat-abdelkerim-abakar @Durgesh4993 please merge this pull request

@mahamat-abdelkerim-abakar  @Durgesh4993  please merge this pull request

**Pull request merged**
