### PR TITLE
Card flip Game

### LINKED ISSUE #176: [Enhancement]: Memory game shows no difference when the matching tiles are found.
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement: I was playing the game when I saw that when the matching tiles were found, nothing different was happening. Also, there was no track of how much points are earned when the tile match is found.

### Describe the solution you'd like

Solution steps:  It can become better if a transition or hover effect could be added in case of a tile match. 
We can add a counter to check for a tile match. When match is found, the count can be increased to a fixed set of points.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by MAYURIKOTHARI299**
Screenshot (29)
Closes #176

### CODE REVIEW

**Comment by MAYURIKOTHARI299** [comment]
@Durgesh4993 please add the label of gssoc 23 and review ,accept the PR under the same.

**Comment by Durgesh4993** [comment]
@MAYURIKOTHARI299 please add screenshort on singleplayer/banner-immage folder

**Comment by MAYURIKOTHARI299** [comment]
@Durgesh4993 I have added the screenshot should I add a screen 
recording too?

**Comment by Durgesh4993** [comment]
@MAYURIKOTHARI299 you can check one more time your game's image is not added

**Comment by MAYURIKOTHARI299** [comment]
@Durgesh4993 I added the images

**Pull request merged**
