### PR TITLE
Improve the Hero Section

### LINKED ISSUE #430: [Enhancement]: Want to improve the ui of home page
### Is your enhancement request related to a problem? Please describe.➕

I want to improve the ui of home page 

### Describe the solution you'd like

**Demo Video**

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/9502827c-8485-4d2f-900d-a9bf6c67e657

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by lakhan06**
## Related Issue*

Closes #430 

## Description
I Add video in home page and made the navbar transparent

## Screenshot Section
image

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/fcaf4da0-f35c-4ed5-bcf3-aca4e4e5402c

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by lakhan06** [comment]
@Durgesh4993 Please Merge this pull request

**Comment by Durgesh4993** [comment]
@lakhan06 Please correct their responsiveness

**Comment by Aman1-coder** [comment]
@lakhan06 Hope you first complete this task

**Comment by lakhan06** [comment]
> @lakhan06 Hope you first complete this task



> @lakhan06 Hope you first complete this task

yes working on it

**Pull request merged**
