### PR TITLE
Digit Dilemma game added

### LINKED ISSUE #811: Digit Dilemma game - GSSOC'23
## Description

This is a logic-based puzzle game where your objective is to fill a grid with the numbers 1 through 9, ensuring that the calculations formed by the numbers in the grid equal the given target numbers.

## Screenshot Section

Digit_Dilemma

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

### PR DESCRIPTION
**Pull request by srujana-16**
## Related Issue*

Closes #811 

## Description

Added a new game. This is a logic-based puzzle game where your objective is to fill a grid with the numbers 1 through 9, ensuring that the calculations formed by the numbers in the grid equal the given target numbers.

## Screenshot Section
Digit_Dilemma

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*

## Task

- [x] Follow Us On social media -
- [x]      <a href="https://github.com/GameSphere-MultiPlayer" target="_blank">GitHub</a>
- [x]      <a href="https://www.linkedin.com/company/gamesphere-multiplayer/" target="_blank">LinkedIn</a>
- [x]     <a href="https://www.youtube.com/@durgesh4993/channels" target="_blank">YouTube</a>
- [x]      <a href="https://discord.com/invite/dakzwdz4ev" target="_blank">Discord</a>

## Enter you User Id's:
LinkedIn: srujana-vanka
<br>GitHub: srujana-16
<br>YouTube: Srujana Vanka
<br>Discord: srujj#1451

If you Follow us in both social medias we provide 'level2' 
*Only First time

### CODE REVIEW

**Comment by srujana-16** [comment]
Just followed, i also resolved the conflicts, please check @mahamat-abdelkerim-abakar

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Add this game into readme.md file

**Comment by srujana-16** [comment]
Already done that @Durgesh4993

**Review by Durgesh4993 — APPROVED** [review]
ok

**Pull request merged**
