### PR TITLE
Virtual Guitar

### PR DESCRIPTION
**Pull request by Tisha6661**
## Related Issue*

Closes #issue_number
#433 

## Description
Virtual Guitar made with features like changing it to bass(4, 5 string) and ukulele. With notes and virtual strings and frets.

## Screenshot Section
image

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@Tisha6661 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by Tisha6661** [comment]
@Durgesh4993 You added level1, how is this game level1, it has 4 instruments and a feature enhancement in the project.

**Comment by Tisha6661** [comment]
I have made 2 games before as well, you added level2 for them, and this was much harder than that.

**Comment by Durgesh4993** [comment]
No Level2 for online multiplyer games only

**Comment by Durgesh4993** [comment]
I have already mentioned in Discord and Repositry

**Comment by Tisha6661** [comment]
I understand that, but this game is about guitar knowledge and notes, it is not bind to singleplayer or multiplayer.

**Comment by Tisha6661** [comment]
It's okay, it's upto you only. Thank you for answering my issue.

**Comment by Durgesh4993** [comment]
Sorry, But this already mentioned in both Discord and Repositry and if you are not satisfy then connect with project admin he said to me give level1 for normal games

**Pull request merged**
