### PR TITLE
Added black-jack game

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Added the game successfully

closes issue number #241

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
home page 👍 image
image


video 👍 
https://www.loom.com/share/8514e88f26264e4ead4204da6ed20890

**Comment by Abhinavcode13** [comment]
Please check this PR @Durgesh4993

**Comment by Durgesh4993** [comment]
@Abhinavcode13 Please add this screnshort into "Sinleplayers-Banner- Image folder"

**Comment by Durgesh4993** [comment]
@Abhinavcode13 Folllow this path "SinglePlayer - Games/Banner - image" then add screensort

**Comment by Abhinavcode13** [comment]
Added @Durgesh4993 please check now !!

**Pull request merged**
