### PR TITLE
Vedio_Game Added

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
## Related Issue*

#645 

## Description

Vedio_Game is Added

## Screenshot Section

Vedio_Game

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/114821855/9c3eaf8c-d531-458c-9a79-8ed2e4ed7775

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by Durgesh4993 — APPROVED** [review]
Please resolve conflict

**Comment by Durgesh4993** [comment]
@Kalivarapubindusree 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by Durgesh4993** [comment]
@Kalivarapubindusree where is code

**Comment by Kalivarapubindusree** [comment]
Vedio_Game Added by Kalivarapubindusree · Pull Request #666 · GameSphere-MultiPlayer_GameSphere - Google Chrome 29-06-2023 22_09_41

See when I resolve the conflict it shows 7files then now 3 files only showing well! I think I need to new PR

**Pull request closed without merging**
