### PR TITLE
Anime clicker game is added

### LINKED ISSUE #613: [New game]: Anime-Clicker
### 🎮 Game Request

Fully functional anime clicker

### Point down the features

Save and load the game if you need to go to sleep for the day, you can come back and your progress will not be erased

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by shraddha761**
## Related Issue*

Closes #613 

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@shraddha761 Resolve conflict

**Comment by shraddha761** [comment]
@Durgesh4993 resolved

**Comment by Durgesh4993** [comment]
@shraddha761 Could you please send me a demo vedio

**Comment by shraddha761** [comment]
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/106100728/b38a21e0-e8b4-46f7-bb5e-5ff17bdf2bdc

@Durgesh4993 please see demo video

**Pull request merged**
