### PR TITLE
Added Geoguesser game

### LINKED ISSUE #722: [New game]: Geoguesser Game
### 🎮 Game Request

The users would be presented with a random Street view(from google streetview api data). They would have to guess the location and mark that on a world map. The closer and more proximate they mark with respect to the true location, the more points they gonna earn. In short, it would be a geography game which would take users to a journey around the world and would challenge their ability to recognize naive surroundings.

### Point down the features

- There would be a start button.
- As the user would start the game, there would be a google street view expanded over whole screen, touchable and interactable, through which the user would attempt to guess the location(city/country) of this street view.
- On a bottom corner would be a world map, where the user would pinpoint his/her guesses.
- The user would be awarded a point based on how close the pinpointed guess is to the actual location of the street view.
- This is the basic game architecture. New street views would emerge one after the other and users would guess their locations and earn points, creating high scores.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by jaivsh**
## Added the Geoguesser game
Closes #722  

## Description
Added Geoguesser, a geography based location-guessing game where the users would have to guess the country location in which they are in from the Google Street View imagery. It takes the players to a journey around the world and tests their abilities to recognize their surroundings.

## Screenshot Section
Geoguesser_screen

## Demo Video Section*
[Demonstrative video lives here](https://drive.google.com/file/d/1-K_l0rcXKGjL_DpMOtoa6Lr9xiimp29X/view?usp=sharing)

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by jaivsh** [comment]
@Durgesh4993 can you please review this pull request? Thanks!

**Comment by Durgesh4993** [comment]
@Killer2-O it is not merged PR

**Comment by Durgesh4993** [comment]
@jaivsh 
Follow Us on Social Media:
LinkedIn: https://www.linkedin.com/company/gamesphere-multiplayer/
GitHub:https://github.com/GameSphere-MultiPlayer

**Comment by jaivsh** [comment]
Hi @Killer2-O @Durgesh4993 The PR mentioned here by @Killer2-O https://github.com/kunjgit/GameZone/pull/2251 has been closed and was not merged in Gamezone. So, I hereby request you guys to please merge my PR. I do affirm that i had proceeded for it's PR and addition after talking to the admins of the Gamezone, through discord. Hence, please merge my PR. Thanks!

**Comment by jaivsh** [comment]
Hi @Killer2-O @Durgesh4993 can u please give any update to this ?

**Pull request closed without merging**
