### PR TITLE
Added Color Blast Game

### LINKED ISSUE #522: [New game]: Bubble Blast Game
### 🎮 Game Request

In This game user need to shoot down the bubbles with ball.

image

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/4a1403c3-a633-4257-928c-c9ac7e94b353

### Point down the features

- Aim and Shoot: Use the mouse to aim the bubble shooter.
-  Adjust the angle and trajectory to your desired position. 
- Click or tap to shoot the bubble towards the top of the grid. 
-  Match Bubbles: Match three or more bubbles of the same color to make them pop and disappear.
-  Your goal is to clear the entire grid of bubbles.
- Score Points: Earn points for each bubble you pop and for clearing the grid.
- Game Over: The game is over if the bubbles reach the bottom of the grid before you clear them all

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by lakhan06**
## Related Issue*

Closes #522 

## Description
 - Aim and Shoot: Use the mouse to aim the bubble shooter.
- Adjust the angle and trajectory to your desired position.
- Click or tap to shoot the bubble towards the top of the grid.
- Match Bubbles: Match three or more bubbles of the same color to make them pop and disappear.
- Your goal is to clear the entire grid of bubbles.
- Score Points: Earn points for each bubble you pop and for clearing the grid.
- Game Over: The game is over if the bubbles reach the bottom of the grid before you clear them all
- 

## Screenshot Section
image

## Demo Video Section*

https://github.com/GameSphere-MultiPlayer/GameSphere/assets/119161467/6a38668d-ff99-47b9-a9d4-96f5a4607a5e

## Checklist 

- [x] I have added image into screensort in "SinglePlayer - Games/Banner - image" in this section*
- [x] I have added game into "additionalpage/game.html"*
- [x] I have added Update main README.md file*
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by lakhan06** [comment]
@Durgesh PLease Merge this

**Comment by Durgesh4993** [comment]
Please Resolve the conflict

**Comment by lakhan06** [comment]
hey @Durgesh4993 i resolved the conflicts

**Comment by lakhan06** [comment]
@Durgesh4993 I am sendind the pr for cards in few minutes

**Comment by Durgesh4993** [comment]
Ok no issue

**Pull request merged**
