### PR TITLE
[ADD]: FLIP THE CARD GAME ✨

### LINKED ISSUE #190: [New game]: FLIP THE CARD
### 🎮 Game Request

Game logic and basic description
- Flip is a timed card memory game. When starting a level, there's a red bar on top of the screen that shows how much time you have left.
- Click the green cards to see what symbol they uncover and try to find the matching symbol underneath the other cards.
- Uncover two matching symbols in a row to eliminate them from the game.
- Eliminate all cards as fast as you can to win the game. Have fun FLIPing!

### Point down the features

Game points
- The game will save your stats locally, via localStorage.
- Click the F to see your stats.
- Click I for these intructions.
- If lost cards appear as LOST,and initially cards appear as FLIP.

### Select The Game Type

Single Player

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
### Related Issue
Fixes/Closes #190 

### Description
- This PR is about adding Flip the card game
- I have noted every details regarding game on the related issue itself

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@0xabdulkhalid can you send a demo vedio and add a screen short on singleplayer/banner folder

**Comment by Durgesh4993** [comment]
path "SinglePlayer - Games/Banner - image"

**Comment by 0xabdulkhalid** [comment]
Yeah sure @Durgesh4993, here's the gameplay


https://github.com/GameSphere-MultiPlayer/GameSphere/assets/92252895/c265827d-8d88-49c2-99de-85694b41cfd4

**Comment by 0xabdulkhalid** [comment]
> path "SinglePlayer - Games/Banner - image"

It's also done, you can check it out!

**Pull request merged**
